[package]
name = "rust_scale_codec_wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
parity-scale-codec = { version = "3.7.5", features = ["derive"] }

[lib]
name = "rust_scale_codec_wrapper"
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.26.0"
